name: main
on:
  push:
    branches:
    - master
    tags:
    - "*"
  pull_request:
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: docker build .
  testandlint:
    name: testandlint
    runs-on: ubuntu-latest
    container: python:3.8-slim-buster
    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build
      run: |
        apt-get update && apt-get -yqq install gcc
        pip -q install pdm
        pdm install
        pdm run black --check .
        pdm run mypy --ignore-missing-imports .
